version: '3'
services:
  rabbitmq: #RabbitMQ server, listens on port 5672 for AMQP connections
    image: "rabbitmq:management"
    hostname: rabbitmq
    ports:
      - "5672:5672" #host:container, server listens on 5672 for AMQP connections
      - "15672:15672" #RabbitMQ Management interface
    networks:
      - app-network

  order_service:
    build: ./order_service
    depends_on:
      - rabbitmq
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=100", "--", "node", "order_service.js"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672


  notification_service:
    build: ./notification_service
    depends_on:
      - rabbitmq
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=100", "--", "node", "notification_service.js"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  inventory_service:
    build: ./inventory_service
    depends_on:
      - rabbitmq
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=100", "--", "node", "inventory_service.js"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672


networks: #containers are in the same network so they can reach each other
  app-network:
    driver: bridge
